# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
title: Synchro Labs
email: support@synchro.io
description: > # this means to ignore newlines until "baseurl:"
  This is the Synchro Labs documentation site (under development). Check back
  later for some real docs.
baseurl: "/SynchroServer" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: synchrolabs
github_username:  SynchroLabs

# Document collections
#
# Data in collections is a little tricky to access from templates.  You have to do this to get the collection:
#
#    {% assign collection = site.collections | where: "label", {{page.collection}} | first %}
#
# Then you can access collection data using {{ collection.yourProp }}
#
collections:
  tutorial:
    permalink: /:collection/:slug
    output: true
    name: 'Tutorial'
  general:
    permalink: /:collection/:slug
    output: true
    name: 'General'
  controls:
    permalink: /:collection/:slug
    output: true
    name: 'Controls'
  samples:
    permalink: /:collection/:slug
    output: true
    name: 'Samples'

# Default layout (per collection)
#
# Note: Anything we put under 'values' will be the default front matter value for pages at the given path, and can this
#       be accessed in a template using {{ page.yourProp }}
#
defaults:
  - scope:
      path: ""
      type: tutorial
    values:
      layout: page
  - scope:
      path: ""
      type: general
    values:
      layout: page
  - scope:
      path: ""
      type: controls
    values:
      layout: page
  - scope:
      path: ""
      type: samples
    values:
      layout: page


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true